# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Martin Podhola
title: Senior System Administrator
email: mpodhola@gmail.com
website: home.vrsocloud.cz

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: martin-podhola-085a60125
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/2019-08-13.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi my name is Martin and I am IT specialist born in 2.8.1985 with 10+ yers of experience in various IT fileds.Adept at computer and software systems, security and privacy. Excellent troubleshooting and organizational skills.

  I am most skilled in: <mark>Linux</mark> and <mark>cooking curry</mark>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universal Production Partners a.s.
        link: upp.cz
        # link_text: boringcompany.com
        sub_title: Linux Administrator "Freelence"
        caption: 2017 - Present
        quote: >
          UPP is Czech largest Visual effects studio in Czech Republic.
        description: | # this will include new lines to allow paragraphs
            My work is maintain Linux based workstations & servers and monitoring of them also hardware/software diagnostics, storages, 
            databases, backup systems , Virtual Servers and Cyber scan development.

      - layout: left
        title: Baldwinprague s.r.o.
        link: baldwinprague.com
        # link_text: boringcompany.com
        sub_title: General it technician "Freelence"
        caption: 2020 - Present
        quote: >
          Baldwinprague is small production and post-production house.
        description: | # this will include new lines to allow paragraphs
            I am providing IT consultations, and general IT services like planing & maintaining server with virtual machines and storage, Network infrastructure, security
            ans also Nextcloud.

      - layout: left
        title: Interprax s.r.o.
        link: interprax.cz
        # link_text: boringcompany.com
        sub_title: General it technician "Freelence"
        caption: 2017 - Present
        quote: >
          Interprax is general practitioner's office
        description: | # this will include new lines to allow paragraphs
            I am providing IT consultations, and general IT services like server proxmox server  virtual machines , windows workstations and backup storage and nwtwork and security.

      - layout: left
        title: Pro-audio s.r.o
        link: pro-audio.cz
        # link_text: boringcompany.com
        sub_title: General it technician "Freelence"
        caption: 2017 - Present
        quote: >
          Pro-aduio is audilogy office
        description: | # this will include new lines to allow paragraphs
            I am providing IT consultations, and general IT services, Usualy windows worksatins, and backup storages and network insfrastructure and securing it.

      - layout: left
        title: IBM
        link: ibm.cz
        # link_text: boringcompany.com
        sub_title: System specialist
        caption: 2012 - 2017
        quote: >
          IBM "big blue" Is an American multinational technology corporation 
        description: | # this will include new lines to allow paragraphs
            My work was maintain IBM Power systems , SAN storages, Databases and tape libraries backup systems.

      - layout: left
        title: GE Money Bank
        link: moneta.cz
        # link_text: boringcompany.com
        sub_title: Aplication Analyst
        caption: 2011 - 2012
        quote: >
          GE Money bank was 4th. largest bank in Czech owned by GE.
        description: | # this will include new lines to allow paragraphs
            My work was developing various APIes and workflows on custom build ESB.

      - layout: left
        title: T-Systems
        link: https://www.t-systems.com/de/en
        # link_text: boringcompany.com
        sub_title: Aplication server specialist
        caption: 2009 - 2011
        quote: >
          Czech part of T-Systems was part of Deutche telecom nowdays is fused with T-Mobile
        description: | # this will include new lines to allow paragraphs
            My role was Supporting various applications and databases for T-Systems clients.

      - layout: left
        title: Hönigsberg & Düvel Datentechnik Czech s.r.o.
        link: 
        # link_text: boringcompany.com
        sub_title: Aplication server specialist
        caption: 2008 - 2009
        quote: >
          H&D was an IT company owned by Volkswagen A.G.
        description: | # this will include new lines to allow paragraphs
            My role was: Supporting PLM Aplication and aplication servers for VW concern.

      - layout: left
        title: Your system s.r.o.
        link: https://ys.cz
        # link_text: boringcompany.com
        sub_title: Windows server specialist
        caption: 2008
        quote: >
          Small Czech IT company
        description: | # this will include new lines to allow paragraphs
            My role was supporting Windows server systems.

      - layout: left
        title: Guinness Store House
        link: https://www.guinness-storehouse.com/en/home
        # link_text: boringcompany.com
        sub_title: Windows server specialist
        caption: 2007-2008
        quote: >
          Largest Irish brewery
        description: | # this will include new lines to allow paragraphs
            My role was best bartender on planet*


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Liberec
        caption: 2004 - 2006
        sub_title: Unfinished Mechatronics
        quote: >
          Faculty of Mechatronics, Informatics and Interdisciplinary Studies
        description: | # this will include new lines to allow paragraphs
          During my time on TUL I learnt lot of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.


      
      - layout: left
        title: SPŠ VOŠ Jičín
        caption: 2000 - 2004
        sub_title: Finished by final exams
        quote: >
          Electronical Computer Systems
        description: | # this will include new lines to allow paragraphs
          During my studies on High school I learned lot about difernt subject which .................

    
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
     #### Soft
     Emapthy, Acitive listening, Verbal/ Non-verbal comminication, <mark>Friendliness </mark>,  Storytrelling , Humor , 
     Tolerance , Collaboration , Sensitivity , Relationship bulding , Meditation , Exchanging ideas , Respectfulness , 
     Negotiation , Delgation , Analysis , Responsibility , Self-motivation , Observation , Initiative , Solution-finding , Innovation , Focus
     

     #### Hard
     <mark>Unix like systems </mark>, Windows systems , SQL , Golang , Shell scripting , Hardware diagnostic , Networking , Virtualization , Storages , 
     basic Web development , Web aplications , <mark>Troubleshooting </mark>, Orchestration "Ansible" , System monitoring "Zabbix", 
     <mark>IT Infrastructure planing </mark> , driving license B,

  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      Czech native

      English advanced

      Russian basic
  



  - title: Hobbies
    layout: text
    content: | # this will include new lines to allow paragraphs   
      <mark>Mountine climbing</mark>, Maps , <mark>Photography</mark>, Reading , Learning , Phylosophy , Cooking , Walking , Cycling , <mark>Traveling</mark> , Cinema, Friends 


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
