# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Martin Podhola
title: Senior System Administrator / Devops engineer
email: mpodhola@gmail.com
website: home.vrsocloud.cz

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: martin-podhola-085a60125
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/fit_128.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an IT specialist with over a decade of diverse experience in the IT industry, including international work experience. I mainly specialize in computer and software systems, security and privacy. I am known for excellent organizational skills and prompt troubleshooting. My key areas of expertise include <mark>Linux</mark> and unexpected talent for <mark>cooking curry</mark>.
content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Datavision s.r.o.
        link: www.datavision.software
        # link_text: boringcompany.com
        sub_title: Head of It/ Devops department
        caption: 2024 - Present
        quote: >
          Gaining hands-on experience collaborating with small development teams focused on vision systems, AI, and machine learning software delivery.
        description: | # this will include new lines to allow paragraphs
          - Lead the IT & DevOps department, managing internal infrastructure built on  <mark>Linux</mark> and other open-source technologies <mark>Proxmox, K3S</mark>.
          - Drive infrastructure automation and the transition to IaC <mark>Terraform, Ansible, bash</mark>, improving scalability and deployment efficiency.
          - Support development teams with vision, AI systems, ensuring smooth production delivery.
          - Support and maintain software development environments, including CI/CD pipelines <mark>Jenkins, Gerrit</mark> and container orchestration and artificial repos <mark>Dockerhub, Nexus</mark>.
          - Oversee network operations, security <mark>Crowdsec, general linux hardening, Routeros</mark>, monitoring <mark>Prometheus, Grafana</mark>, backups <mark>PBS, Borg</mark>, and corporate IT assets across multiple OS environments.
          - Contribute to the design and support of vision and IoT systems<mark>hardware designing</mark> deployed for clients.
          - Ensure ISO 9001 / ISO 27001 compliance through process and security improvements <mark>Department capacity planings</mark>.
          - IT budgeting, vendor management, and procurement.

            **Key achievements include:**
            - Rebuilt deployment automation for delivery of IoT vision systems.
            - Migrated from VMware ESXi → Proxmox.
            - Enhanced perimeter security and led infrastructure relocation.
            - Advanced internal IaC workflows and automations.

      - layout: left
        title: Universal Production Partners a.s.
        link: upp.cz
        # link_text: boringcompany.com
        sub_title: Linux Administrator "Freelance"
        caption: 2017 - 2023
        quote: >
          Worked with cutting-edge technologies at one of Central Europe’s leading VFX studios.
        description: | # this will include new lines to allow paragraphs
          - Managed and maintained <mark>Linux/Unix</mark>,servers, workstations, hypervisors <mark>xcp-ng, xen</mark>, and storage systems, including hardware troubleshooting and performance monitoring.
          - Designed and delivered core infrastructure and storage solutions critical for production pipelines.
          - Participated in automation initiatives <mark>Ansible, bash</mark> to streamline system deployment and maintenance processes.
          - Designed and optimized a high-availability database <mark>mysql, percona backup</mark> cluster with integrated online backup and restore for key pipeline applications.
          - Handled network diagnostics and optimization to improve infrastructure reliability.

            **Key achievements include:**
            - Built and implemented the IT infrastructure for UPP’s Budapest branch.
            - Contributed to the design and development of 3D scanning and rendering infrastructure used in production workflows.

      - layout: left
        title: Interprax s.r.o., Baldwinprague s.r.o., Pro-audio s.r.o.
        sub_title: IT consultant and technician "Site job Freelance"
        caption: 2017 - 2024
        quote: >
          Provided part-time IT support for small offices, handling diverse technical challenges.
        description: | # this will include new lines to allow paragraphs
          - Provided comprehensive IT infrastructure services for small businesses, including medical, post-production, and audiology companies.
          - Designed, deployed, and maintained Linux-based systems, virtualization platforms <mark>Proxmox, MikroTik</mark> network environments.
          - Implemented Nextcloud and other open-source platforms to enable secure data sharing and collaboration.
          - Managed databases <mark>MySQL, PostgreSQL</mark> and ensured system reliability, monitoring, and disaster recovery readiness.
          - Strengthened perimeter and endpoint security, introduced centralized management, and optimized network performance.

          **Key achievements include:**
            - Built and implemented the IT infrastructure for small offices from the ground based on client requirements.


      - layout: left
        title: IBM
        link: ibm.cz
        # link_text: boringcompany.com
        sub_title: System specialist
        caption: 2012 - 2017
        quote: >
          Working at IBM was a great opportunity to gain experience with unique technologies in a mission-critical environment.
        description: | # this will include new lines to allow paragraphs
          - Maintained and supported <mark>Oracle Database</mark> environments with <mark>RAC clusters</mark> on <mark>AIX</mark> Unix systems.
          - Managed IBM Power Systems hardware, including diagnostics and performance tuning.
          - Troubleshot SAN storage, tape libraries as <mark>IBM TSM</mark> backup environments.
          - Contributed to system automation initiatives <mark>ksh, bash</mark> and backup strategy design to improve reliability and efficiency.

          **Key achievements include:**
            - Successfully led several critical incident resolutions, minimizing downtime.
            - Deploy automation scripts that improved system management efficiency.
            - Participated in major system upgrades and migrations with minimal disruption.

      - layout: left
        title: GE Money Bank *"nowadays Moneta"*
        link: moneta.cz
        # link_text: boringcompany.com
        sub_title: Aplication Analyst
        caption: 2011 - 2012
        quote: >
         Gained valuable insight into the internal operations of a large banking institution.
        description: | # this will include new lines to allow paragraphs
          - Developed and maintained APIs and integration workflows on a custom-built Enterprise Service Bus (ESB) platform.
          - Troubleshot and resolved system and integration issues to ensure service reliability.
          - Worked with <mark>Oracle Databases</mark> for data processing, reporting, and system optimization.
          - Created technical documentation and project reports.

          **Key achievements include:**
            - Improved integration processes, enhancing data flow efficiency.
            - Contributed to the successful implementation of new banking services.



      - layout: left
        title: T-Systems
        link: https://www.t-systems.com/de/en
        # link_text: boringcompany.com
        sub_title: Aplication server specialist
        caption: 2009 - 2011
        quote: >
          During my time at T-Systems, I gained essential insight into service-oriented architecture and first-hand experience in leading projects and taking responsibility for key services.
        description: | # this will include new lines to allow paragraphs
          - Supported and maintained applications and databases for enterprise clients using <mark>IBM WebSphere Application Server, Apache Tomcat, and MS SQL</mark>.
          - Provided technical troubleshooting and performance optimization across multiple environments.
          - Acted as Project Manager and Service Owner for the development and support of internal business applications.
          - Collaborated with cross-functional teams to ensure service reliability, change management, and process improvement.

          **Key achievements include:**
            - Successfully managed several high-impact projects, improving application performance and reliability.
            - Developed expertise in application server technologies and enterprise IT solutions.

      - layout: left
        title: Hönigsberg & Düvel Datentechnik Czech s.r.o.
        link:
        # link_text: boringcompany.com
        sub_title: Aplication server specialist
        caption: 2008 - 2009
        quote: >
          Working at H&D was a valuable learning experience that introduced me to the Unix world and gave me insight into how IT operates within large multinational corporations such as Volkswagen.
        description: | # this will include new lines to allow paragraphs
          - Provided application support for Siemens Teamcenter Engineering PLM and <mark>IBM WebSphere Application Server</mark> running on <mark>Sun Microsystems</mark> infrastructure.
          - Monitored, maintained, and optimized enterprise systems supporting Volkswagen AG’s engineering operations.
          - Collaborated with international teams to troubleshoot issues and ensure high service availability.
          - Served on-site in Wolfsburg, gaining valuable international experience working directly for Volkswagen AG.

          **Key achievements include:**
            - Successfully resolved critical application issues, minimizing downtime for engineering teams.
            - Gained international work experience and enhanced cross-cultural communication skills.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical University of Liberec
        caption: 2004 - 2006
        sub_title: Mechatronics (Unfinished)
        quote: >
          Faculty of Mechatronics, Informatics and Interdisciplinary Studies
        description: | # this will include new lines to allow paragraphs
         During my time at TUL, I developed key skills such as teamwork and working to tight deadlines, which I have applied throughout my career. I enjoyed my university experience and gained valuable insight into maintaining a healthy work-life balance.



      - layout: left
        title: SPŠ VOŠ Jičín
        caption: 2000 - 2004
        sub_title: Finished by final exams
        quote: >
          Electronic Computer Systems
        description: | # this will include new lines to allow paragraphs
         During my studies in high school, I acquired the foundational knowledge of electricity and computers, which has been essential to my career.


  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      #### Hard Skills
      - **Unix-like systems:** 15+ years of experience with various distributions — Debian, Ubuntu, RedHat/CentOS, FreeBSD, AIX, macOS.
      - **Automation & Programming:** 13+ years with shell scripting (Bash), Ansible, and Terraform/OpenTofu.
      - **Hardware:** 10+ years of experience in diagnostics and troubleshooting.
      - **System Security:** 5+ years in Linux hardening and security best practices.
      - **Networking:** 10+ years with MikroTik, Linux-based firewalls, VPNs, routing, and switching.
      - **Virtualization:** 10+ years using KVM/QEMU, Proxmox, VMware ESXi, and Xen platforms.
      - **Storage:** 10+ years working with NAS/SAN solutions — NFS, SAMBA, iSCSI, Ceph, S3 object storage.
      - **Monitoring & Alerting:** 10+ years with tools such as Zabbix, Prometheus, and Grafana.
      - **Infrastructure Design:** Designed and built small to mid-scale IT infrastructures from the ground up based on client requirements.
      - **Driving License:** EU category B.

      #### Soft Skills
      - **Active listening & communication (verbal and non-verbal)**
      - **Collaboration & idea exchange**
      - **Responsibility & self-motivation**
      - **Analytical thinking & focus**
      - **Initiative & problem-solving mindset**
      - **Tolerance, friendliness, and sense of humor**
      - **Creativity & innovation in solutions**

  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      Czech native

      English advanced

  - title: Hobbies
    layout: text
    content: | # this will include new lines to allow paragraphs
      My hobbies include <mark>mountain climbing</mark>, maps, <mark>photography</mark>, reading, continuous learning, philosophy, <mark>cooking</mark>, <mark>walking</mark>, cycling, traveling, cinema.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
